# Generated by Django 4.2 on 2026-06-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
